# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/kcs-m/Documents/ieee/mc_stock_sim/mc_stock_sim.srcs/sources_1/ip/cdf_rom/cdf_rom.xci
# IP: The module: 'cdf_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kcs-m/Documents/ieee/mc_stock_sim/mc_stock_sim.gen/sources_1/ip/cdf_rom/cdf_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cdf_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/kcs-m/Documents/ieee/mc_stock_sim/mc_stock_sim.srcs/sources_1/ip/cdf_rom/cdf_rom.xci
# IP: The module: 'cdf_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kcs-m/Documents/ieee/mc_stock_sim/mc_stock_sim.gen/sources_1/ip/cdf_rom/cdf_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cdf_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
