# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/kcs-m/Documents/ieee/fastNormalLutProt/fastNormalLutProt.srcs/sources_1/ip/fp16_exp/fp16_exp.xci
# IP: The module: 'fp16_exp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kcs-m/Documents/ieee/fastNormalLutProt/fastNormalLutProt.gen/sources_1/ip/fp16_exp/fp16_exp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp16_exp'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/kcs-m/Documents/ieee/fastNormalLutProt/fastNormalLutProt.srcs/sources_1/ip/fp16_exp/fp16_exp.xci
# IP: The module: 'fp16_exp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kcs-m/Documents/ieee/fastNormalLutProt/fastNormalLutProt.gen/sources_1/ip/fp16_exp/fp16_exp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp16_exp'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
