# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/kcs-m/Documents/ieee/mc_stock_sim/mc_stock_sim.srcs/sources_1/ip/fp32_mult/fp32_mult.xci
# IP: The module: 'fp32_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kcs-m/Documents/ieee/mc_stock_sim/mc_stock_sim.gen/sources_1/ip/fp32_mult/fp32_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp32_mult'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/kcs-m/Documents/ieee/mc_stock_sim/mc_stock_sim.srcs/sources_1/ip/fp32_mult/fp32_mult.xci
# IP: The module: 'fp32_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/kcs-m/Documents/ieee/mc_stock_sim/mc_stock_sim.gen/sources_1/ip/fp32_mult/fp32_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp32_mult'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
